FROM jupyterhub/jupyterhub:4.1.6

RUN pip install --no-cache-dir \
    dockerspawner==13.0.0 \
    jupyterhub-idle-culler==1.3.1 \
    oauthenticator==16.3.1 \
    jupyterhub-nativeauthenticator==1.3.0
